name: Deploy  Docs

on:
  workflow_dispatch:
  issues:
    types: [ opened, edited ]
  issue_comment:
    types: [ created, edited ]
  push:
    branches:
      - v1_cn
      - v1_en
      - master
    paths:
      - main.py

env:
  GITHUB_NAME: zkpgds
  GITHUB_EMAIL: 843328404@qq.com

jobs:
  sync:
    name: Deploy  Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Deploy Docs
        run: |
          source venv/bin/activate
          python main.py
#          python main.py ${{ secrets.D_T }} ${{ github.repository }}

